services:
  app1:
    build: .
    image: golang-policy-inference-case:latest
    deploy:
      resources:
        limits:
          cpus: "0.125"
          memory: 62.5M
    restart: always

  app2:
    image: golang-policy-inference-case:latest
    deploy:
      resources:
        limits:
          cpus: "0.125"
          memory: 62.5M
    restart: always

  app3:
    image: golang-policy-inference-case:latest
    deploy:
      resources:
        limits:
          cpus: "0.125"
          memory: 62.5M
    restart: always

  app4:
    image: golang-policy-inference-case:latest
    deploy:
      resources:
        limits:
          cpus: "0.125"
          memory: 62.5M
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 96M
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
    restart: always
