services:
  app:
    build: .
    image: golang-policy-inference-case:latest
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 250M
    ports:
      - "8080:8080"
    restart: always
